name: Dismiss Stale PR Approvals
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  dismiss_approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Run BCR PR Reviewer
        uses: bazelbuild/continuous-integration/actions/bcr-pr-reviewer@957b0ac44549a70ccb951361b804d07d955aeb79 # master (same pin as upstream BCR)
        with:
          token: ${{ github.token }}
          action-type: dismiss_approvals
