name: skip_check
on:
  issue_comment:
    types: [created, edited]
permissions:
  contents: read

jobs:
  comment_bot:
    if: startsWith(github.event.comment.body, '@bazel-io skip_check ')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Run bot
        uses: bazelbuild/continuous-integration/actions/bcr-pr-reviewer@957b0ac44549a70ccb951361b804d07d955aeb79 # master (same pin as upstream BCR)
        with:
          token: ${{ github.token }}
          action-type: skip_check
